"""Constants for glyph-bond alignment measurement."""

# Standard Library
import re

MAX_ENDPOINT_TO_LABEL_DISTANCE_FACTOR = 2.6
MIN_ALIGNMENT_DISTANCE_TOLERANCE = 0.07
MIN_BOND_LENGTH_FOR_ANGLE_CHECK = 4.0
LATTICE_ANGLE_TOLERANCE_DEGREES = 1e-6
CANONICAL_LATTICE_ANGLES = tuple(float(angle) for angle in range(0, 360, 30))
GLYPH_BOX_OVERLAP_EPSILON = 0.5
BOND_GLYPH_INTERIOR_EPSILON = 0.35
BOND_GLYPH_GAP_TOLERANCE = 0.65
HAWORTH_RING_SEARCH_RADIUS = 45.0
HAWORTH_RING_MIN_PRIMITIVES = 5
SVG_FLOAT_PATTERN = re.compile(r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?")
LENGTH_ROUND_DECIMALS = 3
ALIGNMENT_DISTANCE_ZERO_EPSILON = 1e-9
HATCH_STROKE_MIN_WIDTH = 0.55
HATCH_STROKE_MAX_WIDTH = 1.35
HATCH_STROKE_MIN_LENGTH = 0.55
HATCH_STROKE_MAX_LENGTH = 4.5
HASHED_CARRIER_MAX_WIDTH = 2.20
HASHED_CARRIER_MIN_LENGTH = 6.0
HASHED_CARRIER_MIN_STROKES = 4
HASHED_STROKE_MAX_DISTANCE_TO_CARRIER = 1.35
HASHED_PERPENDICULAR_TOLERANCE_DEGREES = 25.0
HASHED_SHARED_ENDPOINT_PARALLEL_TOLERANCE_DEGREES = 35.0
MIN_CONNECTOR_LINE_WIDTH = 1.0
GLYPH_CURVED_CHAR_SET = set("OCSQGDU0698")
GLYPH_STEM_CHAR_SET = set("HNPMITFLKEXY147")
ALIGNMENT_INFINITE_LINE_FONT_TOLERANCE_FACTOR = 0.09
DEFAULT_INPUT_GLOB = "output_smoke/archive_matrix_previews/generated/*.svg"
DEFAULT_JSON_REPORT = "output_smoke/glyph_bond_alignment_report.json"
DEFAULT_TEXT_REPORT = "output_smoke/glyph_bond_alignment_report.txt"
DEFAULT_DIAGNOSTIC_SVG_DIR = "output_smoke/glyph_bond_alignment_diagnostics"
